/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rx_test_tools_CPUCounter */

#ifndef _Included_org_rx_test_tools_CPUCounter
#define _Included_org_rx_test_tools_CPUCounter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rx_test_tools_CPUCounter
 * Method:    count
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_rx_test_tools_CPUCounter_count
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
